baseurl      = "https://spyrosmitsis.netlify.app"
title        = "Spyros Mitsis"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  disableReadOtherPosts = false
  enableSharingButtons = true
  enableGlobalLanguageMenu = false
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]

  [[params.social]]
  name = "github"
  url = "https://github.com/SpyrosMitsis"

  [[params.social]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/spyridon-mitsis/"

  [[params.social]]
  name = "kaggle"
  url = "https://www.kaggle.com/SpyrosMitsis"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en.params]
    title = "Spyros Mitsis"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "cd ~/"
      logoHomeLink = "/"

[[menu.main]]
  identifier = "blog"
  name       = "Blog"
  url        = "/posts"